services:
  - type: worker                # এটা web না, কারণ Telegram bot কে background এ চলতে হয়
    name: quotex-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
